### ISSUE TITLE
customize layout grid for lungair

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/lungair-web-application#14]
Customize the LayoutGrid to show the kinds of things we need to show for LungAIR.

One idea:
- Top half of LayoutGrid is an xray view, which will eventually be suitable for viewing or scrolling through a longitudinal series of xrays from the currently selected patient. For now it could be the single "axial" view.
- Bottom left and bottom right quadrants are chart displays based on the currently selected charts. The way I envision charts being selected by default is for the bottom left chart to show some time series info to summarize the patient's trajectory and for the bottom right chart to show the results of the lungair risk analysis.

**Comment by jadh4v** [comment]
- Do we need 3D views?
- Is our primary modality going to be X-Ray only?

**Comment by ebrahimebrahim** [comment]
We do not need 3d views. Yes, xrays only.

**Comment by jadh4v** [comment]
Great, if we don't need 3D, we can also remove the "Rendering" tab since it refers to all the color/optical properties of the volume rendering component. We will then have top-level tabs as: Data (DICOMWeb), Annotations, Remote, EHR.

I will also start with removing the sample data card from the data tab as well. Clean things up and then do the above mentioned layout.

**Comment by ebrahimebrahim** [comment]
> we can also remove the "Rendering" tab

:+1: :+1: 

> I will also start with removing the sample data card from the data tab as well. Clean things up and then do the above mentioned layout.

:+1: :+1: 

> We will then have top-level tabs as: Data (DICOMWeb), Annotations, Remote, EHR.

We will probably majorly reorganize the ModulePanel in the future as the user workflow begins to coalesce, but this works great for now. The main concern in this issue #14 the is the LayoutGrid, i.e. the grid of views shown on the right side
