### ISSUE TITLE
plan out transition to template

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/lungair-web-application#21]
Let's test out https://github.com/floryst/CustomVolViewTemplate

We can discuss here how this goes, when it's appropriate to transition, and how.

This issue can be closed when we have a plan for transition to a volview custom application template.

**Comment by ebrahimebrahim** [comment]
Some of my initial thoughts, assuming we get the custom volview template approach working:

- I wouldn't want to lose the dev history on this repo so I think I'd prefer a big commit that removes the core volview content, replaces it with the custom app template content, and puts the lungair-web-app customizations in the right places.
- We can make a [detach fork request](https://support.github.com/request/fork) from github to make this an ordinary standalone repo.

**Comment by jadh4v** [comment]
I suppose using the detach fork option is inevitable.
I Agree that we should retain our git history. It should be feasible to do a one-time overwrite of the core VolView. In fact, I think it will be more of deletion than overwrite as its a submodule that shouldn't be tracked in this repo.

**Comment by ebrahimebrahim** [comment]
Currently we are waiting for the template to move to a formal repository so that we can be more confident that it has stabilized somewhat. E.g. will it bring in volview as a git submodule or as an npm package?

**Comment by ebrahimebrahim** [comment]
The planning moved to #24 and the task was completed.
