### ISSUE TITLE
Make the python server usable as a remote server

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/lungair-web-application#34]
This may require wrapping it into a flask app.

## Notes:
1. Just testing a remote instance would be a good first step to ensure nothing is broken and works correctly.
2. It might make sense to figure out AWS deployment (#35) at this stage before converting to Flask. Test if the server would work with AWS as-is.
3. Second step could be to add a Flask wrapping if it is deemed necessary for the AWS deployment.
4. Trim down the server to only support LungAir requirements (perhaps bi-directional communication is not required, not maintaining session info). Here uni-directional means that the server cannot send requests to clients and cannot maintain any info about connected clients.

**Comment by jadh4v** [comment]
Notes:
1. Just testing a remote instance would be a good first step to ensure nothing is broken and works correctly.
2. It might make sense to figure out AWS deployment at this stage before converting to Flask. Test if the server would work with AWS as is?
3. Second step could be to add a Flask wrapping if it is deemed necessary for the AWS deployment.
4. Trim down the server to only support LungAir requirements (perhaps bi-directional communication is not required, not maintaining session info).

**Comment by jadh4v** [comment]
I will close this after I test the LungAir's version of the server.
